### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by morfeo9950** [bilalyasin1616/braintreeIntegration#1]
Hi, i want to know if the php server of your integration works with php 7, i was testing in localhost and working well with php 7.3.0, but when i upload it to my web hosting main.php do not shows the token, do i need to change the php version or there is something have to change in my web hosting provider to make it work?, thanks.

**Comment by bilalyasin1616** [comment]
Sorry mate, I haven't tested it in production so can't really tell.
If you figure it out what was the issue do comment here. Thanks

**Comment by morfeo9950** [comment]
Yes i found the solution searching in braintree docs, it only works with php 7.2 and ahead php versions, i had to change host cause it only supports php 7.0, when i change to another hosting with php 7.2 it works showing the token for the client, hope it helps someone...
